// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class AboutAssociation
{
    public int Id { get; set; }

    public string Content { get; set; }

    public string Address { get; set; }

    public string MapsUrl { get; set; }
}