// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class Activity
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string IconClass { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ImageUrl { get; set; }
}