// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class CircleDeparture
{
    public int Id { get; set; }

    public int? CircleId { get; set; }

    public int StudentId { get; set; }

    public DateOnly DepartureDate { get; set; }

    public TimeOnly DepartureTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? TeacherId { get; set; }

    public string Notes { get; set; }

    public virtual QuranCircle Circle { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual Teacher Teacher { get; set; }
}