// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class CircleAttendance
{
    public int Id { get; set; }

    public int? CircleId { get; set; }

    public int StudentId { get; set; }

    public DateTime AttendanceDateTime { get; set; }

    public bool IsHere { get; set; }

    public int? TeacherId { get; set; }

    public DateTime? DepartureDate { get; set; }

    public TimeOnly? DepartureTime { get; set; }

    public virtual QuranCircle Circle { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual Teacher Teacher { get; set; }
}