// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class CircleDay
{
    public int Id { get; set; }

    public int CircleId { get; set; }

    public int DayNumber { get; set; }

    public virtual QuranCircle Circle { get; set; }
}