// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class CommunicationNotification
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string UserType { get; set; }

    public int ChildId { get; set; }

    public string MessageType { get; set; }

    public int MessageId { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ReadDate { get; set; }
}