// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class ContactInfo
{
    public int Id { get; set; }

    public string ContactType { get; set; }

    public string Label { get; set; }

    public string Value { get; set; }

    public int SortOrder { get; set; }
}