// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class Expensife
{
    public int Id { get; set; }

    public string Reason { get; set; }

    public double TotalAmount { get; set; }

    public string Supplier { get; set; }

    public string Notes { get; set; }

    public string AttachmentsFolder { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? TeacherId { get; set; }

    public bool? ForGirls { get; set; }

    public virtual Teacher Teacher { get; set; }
}