// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class FilesManager
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string FilePath { get; set; }
}