// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class FormFieldOption
{
    public int Id { get; set; }

    public int FieldId { get; set; }

    public string OptionLabel { get; set; }

    public string OptionValue { get; set; }

    public int DisplayOrder { get; set; }

    public string OptionText { get; set; }

    public virtual FormField Field { get; set; }
}