// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class FormResponseValue
{
    public int Id { get; set; }

    public int ResponseId { get; set; }

    public int FieldId { get; set; }

    public string FieldValue { get; set; }

    public string OptionValue { get; set; }

    public virtual FormField Field { get; set; }

    public virtual FormResponse Response { get; set; }
}