// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class FormResponse
{
    public int Id { get; set; }

    public int FormId { get; set; }

    public DateTime SubmittedAt { get; set; }

    public string SubmittedBy { get; set; }

    public string SubmitterIp { get; set; }

    public string UserAgent { get; set; }

    public int? StudentId { get; set; }

    public string StudentName { get; set; }

    public string FatherName { get; set; }

    public string FatherMobile { get; set; }

    public DateTime? Birthdate { get; set; }

    public string CircleName { get; set; }

    public virtual DynamicForm Form { get; set; }

    public virtual ICollection<FormResponseValue> FormResponseValues { get; set; } = new List<FormResponseValue>();

    public virtual RegisterForm Student { get; set; }
}