// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class FormField
{
    public int Id { get; set; }

    public int FormId { get; set; }

    public string FieldType { get; set; }

    public string FieldLabel { get; set; }

    public bool IsRequired { get; set; }

    public int DisplayOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public string FieldDescription { get; set; }

    public string FieldName { get; set; }

    public string Placeholder { get; set; }

    public string ValidationPattern { get; set; }

    public bool IsAutoFilled { get; set; }

    public string AutoFillField { get; set; }

    public virtual DynamicForm Form { get; set; }

    public virtual ICollection<FormFieldOption> FormFieldOptions { get; set; } = new List<FormFieldOption>();

    public virtual ICollection<FormResponseValue> FormResponseValues { get; set; } = new List<FormResponseValue>();
}