// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class MeetingsInfo
{
    public int Id { get; set; }

    public int TeacherId { get; set; }

    public string MeetingUrl { get; set; }

    public string ApiResponse { get; set; }

    public DateTime CreatedAt { get; set; }

    public string MeetingName { get; set; }

    public DateTime? StartDateTime { get; set; }

    public string StudentIds { get; set; }

    public string TeacherName { get; set; }

    public byte Status { get; set; }

    public DateTime? EndedAt { get; set; }

    public string TeacherNotes { get; set; }
}