// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MasgedParentMobileAPI.Models;

public partial class NewMasgedTeacherAPIDBContext : DbContext
{
    public NewMasgedTeacherAPIDBContext(DbContextOptions<NewMasgedTeacherAPIDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AboutAssociation> AboutAssociations { get; set; }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<AppSetting> AppSettings { get; set; }

    public virtual DbSet<CardAttendance> CardAttendances { get; set; }

    public virtual DbSet<CircleAttendance> CircleAttendances { get; set; }

    public virtual DbSet<CircleDay> CircleDays { get; set; }

    public virtual DbSet<CircleDeparture> CircleDepartures { get; set; }

    public virtual DbSet<CommunicationNotification> CommunicationNotifications { get; set; }

    public virtual DbSet<Competition> Competitions { get; set; }

    public virtual DbSet<ContactInfo> ContactInfos { get; set; }

    public virtual DbSet<DynamicForm> DynamicForms { get; set; }

    public virtual DbSet<Expensife> Expensives { get; set; }

    public virtual DbSet<FilesManager> FilesManagers { get; set; }

    public virtual DbSet<FormField> FormFields { get; set; }

    public virtual DbSet<FormFieldOption> FormFieldOptions { get; set; }

    public virtual DbSet<FormResponse> FormResponses { get; set; }

    public virtual DbSet<FormResponseValue> FormResponseValues { get; set; }

    public virtual DbSet<HeroSlide> HeroSlides { get; set; }

    public virtual DbSet<HolyQuran> HolyQurans { get; set; }

    public virtual DbSet<MeetingsInfo> MeetingsInfos { get; set; }

    public virtual DbSet<Mosque> Mosques { get; set; }

    public virtual DbSet<NewsItem> NewsItems { get; set; }

    public virtual DbSet<ParentFollowup> ParentFollowups { get; set; }

    public virtual DbSet<ParentNote> ParentNotes { get; set; }

    public virtual DbSet<ParentPanelLog> ParentPanelLogs { get; set; }

    public virtual DbSet<PlanLevel> PlanLevels { get; set; }

    public virtual DbSet<QuranAyah> QuranAyahs { get; set; }

    public virtual DbSet<QuranCircle> QuranCircles { get; set; }

    public virtual DbSet<QuranSurah> QuranSurahs { get; set; }

    public virtual DbSet<ReadyPlan> ReadyPlans { get; set; }

    public virtual DbSet<RegisterForm> RegisterForms { get; set; }

    public virtual DbSet<SocialLink> SocialLinks { get; set; }

    public virtual DbSet<StudentMemorizingCard> StudentMemorizingCards { get; set; }

    public virtual DbSet<StudentPlan> StudentPlans { get; set; }

    public virtual DbSet<StudentPlanItemLog> StudentPlanItemLogs { get; set; }

    public virtual DbSet<StudentPlanMemorizing> StudentPlanMemorizings { get; set; }

    public virtual DbSet<StudentPlanRevise> StudentPlanRevises { get; set; }

    public virtual DbSet<StudentTest> StudentTests { get; set; }

    public virtual DbSet<StudentCircleEnrollment> StudentCircleEnrollments { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<TeacherAttendance> TeacherAttendances { get; set; }

    public virtual DbSet<TeacherMapLocation> TeacherMapLocations { get; set; }

    public virtual DbSet<TeacherNote> TeacherNotes { get; set; }

    public virtual DbSet<TeacherSalary> TeacherSalaries { get; set; }

    public virtual DbSet<TeachersAdminNote> TeachersAdminNotes { get; set; }

    public virtual DbSet<TestBody> TestBodies { get; set; }

    public virtual DbSet<TestHead> TestHeads { get; set; }

    public virtual DbSet<WhatsAppSessionId> WhatsAppSessionIds { get; set; }

    public virtual DbSet<WhatsappPreConfiguredMessage> WhatsappPreConfiguredMessages { get; set; }

    public virtual DbSet<WhatsappTempTable> WhatsappTempTables { get; set; }

    public virtual DbSet<WomanActivity> WomanActivities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AboutAssociation>(entity =>
        {
            entity.ToTable("AboutAssociation");

            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.MapsUrl).HasMaxLength(1000);
        });

        modelBuilder.Entity<Activity>(entity =>
        {
            entity.ToTable("Activity");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IconClass).HasMaxLength(100);
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<AppSetting>(entity =>
        {
            entity.ToTable("AppSetting");

            entity.HasIndex(e => new { e.Key, e.ForGirl }, "IX_AppSetting_Key_ForGirl").IsUnique();

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<CardAttendance>(entity =>
        {
            entity.ToTable("CardAttendance");

            entity.Property(e => e.ActionName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.TheDate).HasColumnType("datetime");

            entity.HasOne(d => d.Student).WithMany(p => p.CardAttendances)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CardAttendance_RegisterForm");
        });

        modelBuilder.Entity<CircleAttendance>(entity =>
        {
            entity.ToTable("CircleAttendance");

            entity.Property(e => e.AttendanceDateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CircleAttendance_AttendanceDateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.DepartureDate).HasColumnType("datetime");
            entity.Property(e => e.IsHere).HasAnnotation("Relational:DefaultConstraintName", "DF_CircleAttendance_IsHere");

            entity.HasOne(d => d.Circle).WithMany(p => p.CircleAttendances)
                .HasForeignKey(d => d.CircleId)
                .HasConstraintName("FK_CircleAttendance_QuranCircle");

            entity.HasOne(d => d.Student).WithMany(p => p.CircleAttendances)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CircleAttendance_RegisterForm");

            entity.HasOne(d => d.Teacher).WithMany(p => p.CircleAttendances)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK_CircleAttendance_Teacher");
        });

        modelBuilder.Entity<CircleDay>(entity =>
        {
            entity.ToTable("CircleDay");

            entity.HasOne(d => d.Circle).WithMany(p => p.CircleDays).HasForeignKey(d => d.CircleId);
        });

        modelBuilder.Entity<CircleDeparture>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CircleDe__3214EC0759EFCC7A");

            entity.ToTable("CircleDeparture");

            entity.HasIndex(e => e.CircleId, "IX_CircleDeparture_CircleId");

            entity.HasIndex(e => e.DepartureDate, "IX_CircleDeparture_DepartureDate");

            entity.HasIndex(e => e.StudentId, "IX_CircleDeparture_StudentId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Notes).HasMaxLength(500);

            entity.HasOne(d => d.Circle).WithMany(p => p.CircleDepartures)
                .HasForeignKey(d => d.CircleId)
                .HasConstraintName("FK_CircleDeparture_QuranCircle");

            entity.HasOne(d => d.Student).WithMany(p => p.CircleDepartures)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CircleDeparture_RegisterForm");

            entity.HasOne(d => d.Teacher).WithMany(p => p.CircleDepartures)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK_CircleDeparture_Teacher");
        });

        modelBuilder.Entity<CommunicationNotification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Communic__3214EC07B2028A35");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MessageType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ReadDate).HasColumnType("datetime");
            entity.Property(e => e.UserType)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<Competition>(entity =>
        {
            entity.ToTable("Competition");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.LinkUrl).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<ContactInfo>(entity =>
        {
            entity.ToTable("ContactInfo");

            entity.Property(e => e.ContactType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Label).HasMaxLength(100);
            entity.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<DynamicForm>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DynamicF__3214EC0788B64C42");

            entity.HasIndex(e => e.FormCode, "UX_DynamicForms_FormCode")
                .IsUnique()
                .HasFilter("([FormCode] IS NOT NULL)");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.FormCode).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Expensife>(entity =>
        {
            entity.Property(e => e.AttachmentsFolder).HasMaxLength(250);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ForGirls)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Expensives_ForGirls");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Supplier)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.Teacher).WithMany(p => p.Expensives)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK_Expensives_Teacher");
        });

        modelBuilder.Entity<FilesManager>(entity =>
        {
            entity.Property(e => e.FilePath).HasMaxLength(500);
            entity.Property(e => e.Name).HasMaxLength(500);
        });

        modelBuilder.Entity<FormField>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormFiel__3214EC07866FD6C7");

            entity.HasIndex(e => new { e.FormId, e.DisplayOrder }, "IX_FormFields_DisplayOrder");

            entity.HasIndex(e => e.FormId, "IX_FormFields_FormId");

            entity.HasIndex(e => new { e.FormId, e.DisplayOrder }, "IX_FormFields_FormId_DisplayOrder");

            entity.Property(e => e.AutoFillField).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FieldDescription).HasMaxLength(500);
            entity.Property(e => e.FieldLabel)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FieldName).HasMaxLength(100);
            entity.Property(e => e.FieldType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Placeholder).HasMaxLength(200);
            entity.Property(e => e.ValidationPattern).HasMaxLength(50);

            entity.HasOne(d => d.Form).WithMany(p => p.FormFields)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK_FormFields_Form");
        });

        modelBuilder.Entity<FormFieldOption>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormFiel__3214EC07B345C1E1");

            entity.HasIndex(e => new { e.FieldId, e.DisplayOrder }, "IX_FormFieldOptions_DisplayOrder");

            entity.HasIndex(e => e.FieldId, "IX_FormFieldOptions_FieldId");

            entity.HasIndex(e => new { e.FieldId, e.DisplayOrder }, "IX_FormFieldOptions_FieldId_DisplayOrder");

            entity.Property(e => e.OptionLabel)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.OptionText).HasMaxLength(200);
            entity.Property(e => e.OptionValue).HasMaxLength(200);

            entity.HasOne(d => d.Field).WithMany(p => p.FormFieldOptions)
                .HasForeignKey(d => d.FieldId)
                .HasConstraintName("FK_FormFieldOptions_Field");
        });

        modelBuilder.Entity<FormResponse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormResp__3214EC075226D3D2");

            entity.HasIndex(e => e.FormId, "IX_FormResponses_FormId");

            entity.HasIndex(e => e.StudentId, "IX_FormResponses_StudentId");

            entity.HasIndex(e => new { e.FormId, e.SubmittedAt }, "IX_FormResponses_SubmittedAt");

            entity.Property(e => e.CircleName).HasMaxLength(100);
            entity.Property(e => e.FatherMobile).HasMaxLength(20);
            entity.Property(e => e.FatherName).HasMaxLength(150);
            entity.Property(e => e.StudentName).HasMaxLength(150);
            entity.Property(e => e.SubmittedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SubmittedBy).HasMaxLength(100);
            entity.Property(e => e.SubmitterIp).HasMaxLength(45);
            entity.Property(e => e.UserAgent).HasMaxLength(500);

            entity.HasOne(d => d.Form).WithMany(p => p.FormResponses)
                .HasForeignKey(d => d.FormId)
                .HasConstraintName("FK_FormResponses_Form");

            entity.HasOne(d => d.Student).WithMany(p => p.FormResponses)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK_FormResponses_RegisterForm");
        });

        modelBuilder.Entity<FormResponseValue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FormResp__3214EC07E9081CB5");

            entity.HasIndex(e => e.ResponseId, "IX_FormResponseValues_ResponseId");

            entity.HasIndex(e => e.FieldId, "IX_ResponseValues_FieldId");

            entity.HasIndex(e => e.ResponseId, "IX_ResponseValues_ResponseId");

            entity.Property(e => e.OptionValue).HasMaxLength(200);

            entity.HasOne(d => d.Field).WithMany(p => p.FormResponseValues)
                .HasForeignKey(d => d.FieldId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResponseValues_Field");

            entity.HasOne(d => d.Response).WithMany(p => p.FormResponseValues)
                .HasForeignKey(d => d.ResponseId)
                .HasConstraintName("FK_ResponseValues_Response");
        });

        modelBuilder.Entity<HeroSlide>(entity =>
        {
            entity.ToTable("HeroSlide");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
        });

        modelBuilder.Entity<HolyQuran>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HolyQura__3213E83F104981BC");

            entity.ToTable("HolyQuran");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AyaNo).HasColumnName("aya_no");
            entity.Property(e => e.AyaTextEmlaey).HasColumnName("aya_text_emlaey");
            entity.Property(e => e.HezbNo).HasColumnName("hezb_no");
            entity.Property(e => e.HezbQuarter).HasColumnName("hezb_quarter");
            entity.Property(e => e.Jozz).HasColumnName("jozz");
            entity.Property(e => e.LineEnd).HasColumnName("line_end");
            entity.Property(e => e.LineStart).HasColumnName("line_start");
            entity.Property(e => e.Page).HasColumnName("page");
            entity.Property(e => e.SuraNameAr)
                .HasMaxLength(100)
                .HasColumnName("sura_name_ar");
            entity.Property(e => e.SuraNo).HasColumnName("sura_no");
        });

        modelBuilder.Entity<MeetingsInfo>(entity =>
        {
            entity.ToTable("MeetingsInfo");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MeetingName).HasMaxLength(255);
            entity.Property(e => e.MeetingUrl).IsRequired();
            entity.Property(e => e.StartDateTime).HasColumnType("datetime");
            entity.Property(e => e.TeacherName).HasMaxLength(200);
            entity.Property(e => e.Status).HasDefaultValue((byte)0);
            entity.Property(e => e.EndedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Mosque>(entity =>
        {
            entity.ToTable("Mosque");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.GoogleMapsUrl).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<NewsItem>(entity =>
        {
            entity.ToTable("NewsItem");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.LinkUrl).HasMaxLength(500);
            entity.Property(e => e.NewsDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300);
        });

        modelBuilder.Entity<ParentFollowup>(entity =>
        {
            entity.HasKey(e => e.StudentId);

            entity.ToTable("ParentFollowup");

            entity.Property(e => e.StudentId).ValueGeneratedNever();
            entity.Property(e => e.Address)
                .HasMaxLength(500)
                .HasColumnName("address");
            entity.Property(e => e.HealthCondition)
                .HasMaxLength(500)
                .HasColumnName("healthCondition");
            entity.Property(e => e.HealthDetails)
                .HasMaxLength(500)
                .HasColumnName("healthDetails");
            entity.Property(e => e.LearningDifficulties)
                .HasMaxLength(500)
                .HasColumnName("learningDifficulties");
            entity.Property(e => e.LearningDifficultiesNotes)
                .HasMaxLength(500)
                .HasColumnName("learningDifficultiesNotes");
            entity.Property(e => e.MaritalStatus)
                .HasMaxLength(500)
                .HasColumnName("maritalStatus");
            entity.Property(e => e.PhotoPath)
                .HasMaxLength(500)
                .HasColumnName("photoPath");

            entity.HasOne(d => d.Student).WithOne(p => p.ParentFollowup)
                .HasForeignKey<ParentFollowup>(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParentFollowup_RegisterForm");
        });

        modelBuilder.Entity<ParentNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ParentNo__3214EC07C6405037");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.ReadDate).HasColumnType("datetime");
            entity.Property(e => e.TeacherReply).HasMaxLength(500);
        });

        modelBuilder.Entity<ParentPanelLog>(entity =>
        {
            entity.ToTable("ParentPanelLog");

            entity.HasIndex(e => e.AccessDateTime, "IX_ParentPanelLog_AccessDateTime");

            entity.HasIndex(e => e.ParentMobile, "IX_ParentPanelLog_ParentMobile");

            entity.HasIndex(e => e.StudentId, "IX_ParentPanelLog_StudentId");

            entity.Property(e => e.AccessDateTime).HasColumnType("datetime");
            entity.Property(e => e.ParentMobile)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Student).WithMany(p => p.ParentPanelLogs)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ParentPanelLog_RegisterForm");
        });

        modelBuilder.Entity<PlanLevel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlanLeve__3214EC071807E688");

            entity.ToTable("PlanLevel");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlanLevel_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.LevelName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<QuranAyah>(entity =>
        {
            entity.ToTable("QuranAyah");

            entity.HasIndex(e => e.SurahId, "IX_QuranAyah_SurahId");

            entity.HasOne(d => d.Surah).WithMany(p => p.QuranAyahs)
                .HasForeignKey(d => d.SurahId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuranAyah_QuranSurah");
        });

        modelBuilder.Entity<QuranCircle>(entity =>
        {
            entity.ToTable("QuranCircle");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_QuranCircle_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ForGirls)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_QuranCircle_ForGirls");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.QuranCircleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuranCircle_Teacher1");

            entity.HasOne(d => d.Teacher).WithMany(p => p.QuranCircleTeachers)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK_QuranCircle_Teacher");
        });

        modelBuilder.Entity<QuranSurah>(entity =>
        {
            entity.ToTable("QuranSurah");

            entity.Property(e => e.NameAr)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<ReadyPlan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReadyPla__3214EC0781FBAC75");

            entity.ToTable("ReadyPlan");

            entity.HasIndex(e => new { e.FromDate, e.ToDate }, "IX_ReadyPlan_Dates");

            entity.HasIndex(e => e.PlanLevelId, "IX_ReadyPlan_PlanLevelId");

            entity.HasIndex(e => new { e.FromSurahId, e.ToSurahId }, "IX_ReadyPlan_Surahs");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.PlanLevel).WithMany(p => p.ReadyPlans)
                .HasForeignKey(d => d.PlanLevelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReadyPlan_PlanLevel");
        });

        modelBuilder.Entity<RegisterForm>(entity =>
        {
            entity.ToTable("RegisterForm");

            entity.Property(e => e.Birthdate).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RegisterForm_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.FatherName).HasMaxLength(300);
            entity.Property(e => e.FatherPhone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FatherPhone2).HasMaxLength(50);
            entity.Property(e => e.FullName).HasMaxLength(500);
            entity.Property(e => e.IsSpecial).HasAnnotation("Relational:DefaultConstraintName", "DF_RegisterForm_IsSpecial");
            entity.Property(e => e.LearnCertificate).HasMaxLength(500);
            entity.Property(e => e.StudentGender)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.StudentName)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.StudentPhone).HasMaxLength(50);
            entity.Property(e => e.ThePassword).HasMaxLength(250);

            entity.HasOne(d => d.PlanLevel).WithMany(p => p.RegisterForms)
                .HasForeignKey(d => d.PlanLevelId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_RegisterForm_PlanLevel");

            entity.HasOne(d => d.QuranCircle).WithMany(p => p.RegisterForms)
                .HasForeignKey(d => d.QuranCircleId)
                .HasConstraintName("FK_RegisterForm_QuranCircle");

            entity.HasOne(d => d.WomanActivityTypeNavigation).WithMany(p => p.RegisterForms)
                .HasForeignKey(d => d.WomanActivityType)
                .HasConstraintName("FK_RegisterForm_WomanActivity");
        });

        modelBuilder.Entity<SocialLink>(entity =>
        {
            entity.ToTable("SocialLink");

            entity.Property(e => e.IconClass).HasMaxLength(100);
            entity.Property(e => e.PlatformName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<StudentMemorizingCard>(entity =>
        {
            entity.ToTable("StudentMemorizingCard");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StudentMemorizingCard_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DayName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsDone)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsSaveDone)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.ParentNotes).HasMaxLength(500);
            entity.Property(e => e.SurahName).HasMaxLength(500);
            entity.Property(e => e.TestFrom)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TestTo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TheType)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Circle).WithMany(p => p.StudentMemorizingCards)
                .HasForeignKey(d => d.CircleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentMemorizingCard_QuranCircle");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentMemorizingCards)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentMemorizingCard_RegisterForm");

            entity.HasOne(d => d.Teacher).WithMany(p => p.StudentMemorizingCards)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentMemorizingCard_Teacher");
        });

        modelBuilder.Entity<StudentPlan>(entity =>
        {
            entity.ToTable("StudentPlan");

            entity.HasIndex(e => e.StudentId, "IX_StudentPlan_StudentId");

            entity.HasIndex(e => new { e.StudentId, e.PlanFromDate, e.PlanToDate }, "IX_StudentPlan_StudentId_Dates");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Student).WithMany(p => p.StudentPlans)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlan_RegisterForm");
        });

        modelBuilder.Entity<StudentPlanItemLog>(entity =>
        {
            entity.ToTable("StudentPlanItemLog");

            entity.HasIndex(e => e.LoggedAt, "IX_StudentPlanItemLog_LoggedAt").IsDescending();

            entity.HasIndex(e => e.PlanId, "IX_StudentPlanItemLog_PlanId");

            entity.HasIndex(e => new { e.StudentId, e.RowKey }, "IX_StudentPlanItemLog_StudentId_RowKey");

            entity.Property(e => e.LoggedAt).HasColumnType("datetime");
            entity.Property(e => e.RowKey)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Plan).WithMany(p => p.StudentPlanItemLogs)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanItemLog_StudentPlan");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentPlanItemLogs)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanItemLog_RegisterForm");

            entity.HasOne(d => d.Teacher).WithMany(p => p.StudentPlanItemLogs)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanItemLog_Teacher");
        });

        modelBuilder.Entity<StudentPlanMemorizing>(entity =>
        {
            entity.ToTable("StudentPlanMemorizing");

            entity.Property(e => e.MemorizationLevel)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Plan).WithMany(p => p.StudentPlanMemorizings)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanMemorizing_StudentPlan");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentPlanMemorizings)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanMemorizing_RegisterForm");

            entity.HasOne(d => d.Surah).WithMany(p => p.StudentPlanMemorizings)
                .HasForeignKey(d => d.SurahId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanMemorizing_QuranSurah");
        });

        modelBuilder.Entity<StudentPlanRevise>(entity =>
        {
            entity.ToTable("StudentPlanRevise");

            entity.Property(e => e.MemorizationLevel)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Plan).WithMany(p => p.StudentPlanRevises)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanRevise_StudentPlan");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentPlanRevises)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanRevise_RegisterForm");

            entity.HasOne(d => d.Surah).WithMany(p => p.StudentPlanRevises)
                .HasForeignKey(d => d.SurahId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentPlanRevise_QuranSurah");
        });

        modelBuilder.Entity<StudentTest>(entity =>
        {
            entity.ToTable("StudentTest");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StudentTest_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.TestFrom)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.TestName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.TestTo)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.Circle).WithMany(p => p.StudentTests)
                .HasForeignKey(d => d.CircleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentTest_QuranCircle");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentTests)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentTest_RegisterForm");

            entity.HasOne(d => d.Teacher).WithMany(p => p.StudentTests)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentTest_Teacher");
        });

        modelBuilder.Entity<StudentCircleEnrollment>(entity =>
        {
            entity.ToTable("StudentCircleEnrollment");

            entity.HasIndex(e => e.CircleId, "IX_StudentCircleEnrollment_CircleId");
            entity.HasIndex(e => e.StudentId, "IX_StudentCircleEnrollment_StudentId");
            entity.HasIndex(e => new { e.StudentId, e.EndDate }, "IX_StudentCircleEnrollment_StudentId_EndDate");

            entity.Property(e => e.EndDate).HasColumnType("datetime2");
            entity.Property(e => e.StartDate).HasColumnType("datetime2");

            entity.HasOne(d => d.AssignedByTeacher).WithMany()
                .HasForeignKey(d => d.AssignedByTeacherId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_StudentCircleEnrollment_Teacher");

            entity.HasOne(d => d.Circle).WithMany()
                .HasForeignKey(d => d.CircleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentCircleEnrollment_QuranCircle");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentCircleEnrollments)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StudentCircleEnrollment_RegisterForm");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.ToTable("Teacher");

            entity.HasIndex(e => e.AttendanceFingerprintHash, "IX_Teacher_AttendanceFingerprintHash").HasFilter("([AttendanceFingerprintHash] IS NOT NULL)");

            entity.Property(e => e.AttendanceFingerprintHash)
                .HasMaxLength(64)
                .HasComment("SHA-256 hex hash of teacher-bound enrollment secret for attendance/departure verification. NULL until first enrollment.");
            entity.Property(e => e.BaseSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Image).HasMaxLength(250);
            entity.Property(e => e.IsGirlTeacher)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Teacher_IsGirlTeacher");
            entity.Property(e => e.Mobile).HasMaxLength(15);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UsersManage).HasAnnotation("Relational:DefaultConstraintName", "DF_Teacher_UsersManage");
        });

        modelBuilder.Entity<TeacherAttendance>(entity =>
        {
            entity.ToTable("TeacherAttendance");

            entity.HasIndex(e => e.AttendanceDateTime, "IX_TeacherAttendance_AttendanceDateTime");

            entity.HasIndex(e => e.DepartureDateTime, "IX_TeacherAttendance_DepartureDateTime");

            entity.HasIndex(e => e.TeacherId, "IX_TeacherAttendance_TeacherId");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TeacherAttendances)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeacherAttendance_Teacher");
        });

        modelBuilder.Entity<TeacherMapLocation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TeacherM__3214EC072C660F65");

            entity.ToTable("TeacherMapLocation");

            entity.Property(e => e.Latitude).HasMaxLength(50);
            entity.Property(e => e.Longitude).HasMaxLength(50);
            entity.Property(e => e.MapUrl)
                .IsRequired()
                .HasColumnName("MapURL");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TeacherMapLocations)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK_TeacherMapLocation_Teacher");
        });

        modelBuilder.Entity<TeacherNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TeacherN__3214EC078B4FE49F");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Notes).IsRequired();
            entity.Property(e => e.ReadDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<TeacherSalary>(entity =>
        {
            entity.ToTable("TeacherSalary");

            entity.HasIndex(e => new { e.Month, e.Year }, "IX_TeacherSalary_MonthYear");

            entity.HasIndex(e => e.Status, "IX_TeacherSalary_Status");

            entity.HasIndex(e => e.TeacherId, "IX_TeacherSalary_TeacherId");

            entity.HasIndex(e => new { e.TeacherId, e.Month, e.Year }, "IX_TeacherSalary_Unique").IsUnique();

            entity.Property(e => e.BaseSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CalculatedSalary).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TotalHours).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TeacherSalaries)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeacherSalary_Teacher");
        });

        modelBuilder.Entity<TeachersAdminNote>(entity =>
        {
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Note).IsRequired();
            entity.Property(e => e.ReadTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<TestBody>(entity =>
        {
            entity.ToTable("TestBody");

            entity.HasIndex(e => e.TestHeadId, "IX_TestBody_TestHeadId");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.QuestionName).HasMaxLength(200);

            entity.HasOne(d => d.TestHead).WithMany(p => p.TestBodies)
                .HasForeignKey(d => d.TestHeadId)
                .HasConstraintName("FK_TestBody_TestHead");
        });

        modelBuilder.Entity<TestHead>(entity =>
        {
            entity.ToTable("TestHead");

            entity.HasIndex(e => e.StudentId, "IX_TestHead_StudentId");

            entity.HasIndex(e => e.TestDate, "IX_TestHead_TestDate");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.FinalResult).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Grade).HasMaxLength(100);
            entity.Property(e => e.HezbNumber).HasMaxLength(100);
            entity.Property(e => e.MemorizationScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.RevisionScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.SurahName).HasMaxLength(500);
            entity.Property(e => e.TajweedScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TestDate).HasColumnType("datetime");
            entity.Property(e => e.TestFrom).HasMaxLength(500);
            entity.Property(e => e.TestName).HasMaxLength(500);
            entity.Property(e => e.TestTo).HasMaxLength(500);
            entity.Property(e => e.TestType).HasMaxLength(150);
            entity.Property(e => e.TotalScore).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Circle).WithMany(p => p.TestHeads)
                .HasForeignKey(d => d.CircleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TestHead_QuranCircle");

            entity.HasOne(d => d.Student).WithMany(p => p.TestHeads)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TestHead_RegisterForm");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TestHeads)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TestHead_Teacher");
        });

        modelBuilder.Entity<WhatsAppSessionId>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValue(1);
            entity.Property(e => e.MasgedApiKey).HasMaxLength(500);
        });

        modelBuilder.Entity<WhatsappPreConfiguredMessage>(entity =>
        {
            entity.Property(e => e.Event)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.WhatsappMessage)
                .IsRequired()
                .HasMaxLength(2000);
        });

        modelBuilder.Entity<WhatsappTempTable>(entity =>
        {
            entity.ToTable("whatsapp_temp_table");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Image).HasColumnName("image");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.Mobile)
                .HasMaxLength(50)
                .HasColumnName("mobile");
        });

        modelBuilder.Entity<WomanActivity>(entity =>
        {
            entity.ToTable("WomanActivity");

            entity.Property(e => e.IsVisible)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_WomanActivity_IsVisible");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}