// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class ParentPanelLog
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public string ParentMobile { get; set; }

    public DateTime AccessDateTime { get; set; }

    public virtual RegisterForm Student { get; set; }
}