// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class ParentFollowup
{
    public int StudentId { get; set; }

    public string Address { get; set; }

    public string MaritalStatus { get; set; }

    public string HealthCondition { get; set; }

    public string HealthDetails { get; set; }

    public string LearningDifficulties { get; set; }

    public string PhotoPath { get; set; }

    public string LearningDifficultiesNotes { get; set; }

    public virtual RegisterForm Student { get; set; }
}