// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class ParentNote
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsRead { get; set; }

    public DateTime? ReadDate { get; set; }

    public int? ReadByTeacherId { get; set; }

    public string TeacherReply { get; set; }
}