// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class PlanLevel
{
    public int Id { get; set; }

    public string LevelName { get; set; }

    public byte UnitType { get; set; }

    public int Quantity { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedByTeacherId { get; set; }

    public virtual ICollection<ReadyPlan> ReadyPlans { get; set; } = new List<ReadyPlan>();

    public virtual ICollection<RegisterForm> RegisterForms { get; set; } = new List<RegisterForm>();
}