// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class QuranSurah
{
    public int Id { get; set; }

    public string NameAr { get; set; }

    public int? SortOrder { get; set; }

    public virtual ICollection<QuranAyah> QuranAyahs { get; set; } = new List<QuranAyah>();

    public virtual ICollection<StudentPlanMemorizing> StudentPlanMemorizings { get; set; } = new List<StudentPlanMemorizing>();

    public virtual ICollection<StudentPlanRevise> StudentPlanRevises { get; set; } = new List<StudentPlanRevise>();
}