// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class QuranAyah
{
    public int Id { get; set; }

    public int SurahId { get; set; }

    public int AyahNumber { get; set; }

    public virtual QuranSurah Surah { get; set; }
}