// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class QuranCircle
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public int CreatedBy { get; set; }

    public int? TeacherId { get; set; }

    public bool? ForGirls { get; set; }

    public virtual ICollection<CircleAttendance> CircleAttendances { get; set; } = new List<CircleAttendance>();

    public virtual ICollection<CircleDay> CircleDays { get; set; } = new List<CircleDay>();

    public virtual ICollection<CircleDeparture> CircleDepartures { get; set; } = new List<CircleDeparture>();

    public virtual Teacher CreatedByNavigation { get; set; }

    public virtual ICollection<RegisterForm> RegisterForms { get; set; } = new List<RegisterForm>();

    public virtual ICollection<StudentMemorizingCard> StudentMemorizingCards { get; set; } = new List<StudentMemorizingCard>();

    public virtual ICollection<StudentTest> StudentTests { get; set; } = new List<StudentTest>();

    public virtual Teacher Teacher { get; set; }

    public virtual ICollection<TestHead> TestHeads { get; set; } = new List<TestHead>();
}