// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class ReadyPlan
{
    public int Id { get; set; }

    public int PlanLevelId { get; set; }

    public int FromSurahId { get; set; }

    public int ToSurahId { get; set; }

    public DateOnly FromDate { get; set; }

    public DateOnly ToDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? FromAyah { get; set; }

    public int? ToAyah { get; set; }

    public int? FromJozz { get; set; }

    public int? ToJozz { get; set; }

    public int? CreatedByTeacherId { get; set; }

    public virtual PlanLevel PlanLevel { get; set; }
}