// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class RegisterForm
{
    public int Id { get; set; }

    public string StudentName { get; set; }

    public string FatherName { get; set; }

    public int Age { get; set; }

    public string StudentPhone { get; set; }

    public string FatherPhone { get; set; }

    public string FatherPhone2 { get; set; }

    public string StudentGender { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? QuranCircleId { get; set; }

    public DateTime? Birthdate { get; set; }

    public int? IsGirl { get; set; }

    public string FullName { get; set; }

    public int? WomanActivityType { get; set; }

    public string LearnCertificate { get; set; }

    public string ThePassword { get; set; }

    public bool IsSpecial { get; set; }

    public bool IsElite { get; set; }

    public int? PlanLevelId { get; set; }

    public virtual ICollection<CardAttendance> CardAttendances { get; set; } = new List<CardAttendance>();

    public virtual ICollection<CircleAttendance> CircleAttendances { get; set; } = new List<CircleAttendance>();

    public virtual ICollection<CircleDeparture> CircleDepartures { get; set; } = new List<CircleDeparture>();

    public virtual ICollection<FormResponse> FormResponses { get; set; } = new List<FormResponse>();

    public virtual ParentFollowup ParentFollowup { get; set; }

    public virtual ICollection<ParentPanelLog> ParentPanelLogs { get; set; } = new List<ParentPanelLog>();

    public virtual PlanLevel PlanLevel { get; set; }

    public virtual QuranCircle QuranCircle { get; set; }

    public virtual ICollection<StudentMemorizingCard> StudentMemorizingCards { get; set; } = new List<StudentMemorizingCard>();

    public virtual ICollection<StudentPlanItemLog> StudentPlanItemLogs { get; set; } = new List<StudentPlanItemLog>();

    public virtual ICollection<StudentPlanMemorizing> StudentPlanMemorizings { get; set; } = new List<StudentPlanMemorizing>();

    public virtual ICollection<StudentPlanRevise> StudentPlanRevises { get; set; } = new List<StudentPlanRevise>();

    public virtual ICollection<StudentPlan> StudentPlans { get; set; } = new List<StudentPlan>();

    public virtual ICollection<StudentTest> StudentTests { get; set; } = new List<StudentTest>();

    public virtual ICollection<StudentCircleEnrollment> StudentCircleEnrollments { get; set; } = new List<StudentCircleEnrollment>();

    public virtual ICollection<TestHead> TestHeads { get; set; } = new List<TestHead>();

    public virtual WomanActivity WomanActivityTypeNavigation { get; set; }
}