// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class SocialLink
{
    public int Id { get; set; }

    public string PlatformName { get; set; }

    public string Url { get; set; }

    public string IconClass { get; set; }

    public int SortOrder { get; set; }
}