// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class StudentTest
{
    public int Id { get; set; }

    public string TestName { get; set; }

    public string TestFrom { get; set; }

    public string TestTo { get; set; }

    public int TeacherId { get; set; }

    public int StudentId { get; set; }

    public int CircleId { get; set; }

    public int TestDegree { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Notes { get; set; }

    public virtual QuranCircle Circle { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual Teacher Teacher { get; set; }
}