// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class StudentPlanItemLog
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public string RowKey { get; set; }

    public string Status { get; set; }

    public int TeacherId { get; set; }

    public DateTime LoggedAt { get; set; }

    public int PlanId { get; set; }

    public virtual StudentPlan Plan { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual Teacher Teacher { get; set; }
}