// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class StudentPlan
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public string Name { get; set; }

    public DateOnly PlanFromDate { get; set; }

    public DateOnly PlanToDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsArchived { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual ICollection<StudentPlanItemLog> StudentPlanItemLogs { get; set; } = new List<StudentPlanItemLog>();

    public virtual ICollection<StudentPlanMemorizing> StudentPlanMemorizings { get; set; } = new List<StudentPlanMemorizing>();

    public virtual ICollection<StudentPlanRevise> StudentPlanRevises { get; set; } = new List<StudentPlanRevise>();
}