// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class StudentPlanMemorizing
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public string MemorizationLevel { get; set; }

    public int SurahId { get; set; }

    public int FromAyahNumber { get; set; }

    public int ToAyahNumber { get; set; }

    public DateOnly PlanDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateOnly? PlanEndDate { get; set; }

    public string Status { get; set; }

    public int PlanId { get; set; }

    public DateOnly? MemorizeDate { get; set; }

    public DateOnly? ReviseDate { get; set; }

    public virtual StudentPlan Plan { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual QuranSurah Surah { get; set; }
}