// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace MasgedParentMobileAPI.Models;

public partial class StudentCircleEnrollment
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int CircleId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? AssignedByTeacherId { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual QuranCircle Circle { get; set; }

    public virtual Teacher AssignedByTeacher { get; set; }
}
