// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class Teacher
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool UsersManage { get; set; }

    public bool? IsGirlTeacher { get; set; }

    public string Image { get; set; }

    public bool IsViewOnly { get; set; }

    public decimal? BaseSalary { get; set; }

    /// <summary>
    /// SHA-256 hex hash of teacher-bound enrollment secret for attendance/departure verification. NULL until first enrollment.
    /// </summary>
    public string AttendanceFingerprintHash { get; set; }

    public virtual ICollection<CircleAttendance> CircleAttendances { get; set; } = new List<CircleAttendance>();

    public virtual ICollection<CircleDeparture> CircleDepartures { get; set; } = new List<CircleDeparture>();

    public virtual ICollection<Expensife> Expensives { get; set; } = new List<Expensife>();

    public virtual ICollection<QuranCircle> QuranCircleCreatedByNavigations { get; set; } = new List<QuranCircle>();

    public virtual ICollection<QuranCircle> QuranCircleTeachers { get; set; } = new List<QuranCircle>();

    public virtual ICollection<StudentMemorizingCard> StudentMemorizingCards { get; set; } = new List<StudentMemorizingCard>();

    public virtual ICollection<StudentPlanItemLog> StudentPlanItemLogs { get; set; } = new List<StudentPlanItemLog>();

    public virtual ICollection<StudentTest> StudentTests { get; set; } = new List<StudentTest>();

    public virtual ICollection<TeacherAttendance> TeacherAttendances { get; set; } = new List<TeacherAttendance>();

    public virtual ICollection<TeacherMapLocation> TeacherMapLocations { get; set; } = new List<TeacherMapLocation>();

    public virtual ICollection<TeacherSalary> TeacherSalaries { get; set; } = new List<TeacherSalary>();

    public virtual ICollection<TestHead> TestHeads { get; set; } = new List<TestHead>();
}