// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class TeacherMapLocation
{
    public int Id { get; set; }

    public int TeacherId { get; set; }

    public string MapUrl { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public virtual Teacher Teacher { get; set; }
}