// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class TeachersAdminNote
{
    public int Id { get; set; }

    public int TeacherId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsRead { get; set; }

    public DateTime? ReadTime { get; set; }
}