// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class TeacherSalary
{
    public int Id { get; set; }

    public int TeacherId { get; set; }

    public int Month { get; set; }

    public int Year { get; set; }

    public decimal? BaseSalary { get; set; }

    public int DaysAttended { get; set; }

    public decimal TotalHours { get; set; }

    public DateTime? DayOffDate { get; set; }

    public decimal CalculatedSalary { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public int? ApprovedBy { get; set; }

    public virtual Teacher Teacher { get; set; }
}