// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class TeacherAttendance
{
    public int Id { get; set; }

    public int TeacherId { get; set; }

    public DateTime AttendanceDateTime { get; set; }

    public DateTime? DepartureDateTime { get; set; }

    public double? AttendanceLatitude { get; set; }

    public double? AttendanceLongitude { get; set; }

    public double? DepartureLatitude { get; set; }

    public double? DepartureLongitude { get; set; }

    public virtual Teacher Teacher { get; set; }
}