// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class TestHead
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int CircleId { get; set; }

    public int TeacherId { get; set; }

    public string TestFrom { get; set; }

    public string TestTo { get; set; }

    public DateTime TestDate { get; set; }

    public decimal FinalResult { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string TestType { get; set; }

    public string TestName { get; set; }

    public string SurahName { get; set; }

    public string HezbNumber { get; set; }

    public decimal? MemorizationScore { get; set; }

    public decimal? TajweedScore { get; set; }

    public decimal? RevisionScore { get; set; }

    public decimal? TotalScore { get; set; }

    public string Grade { get; set; }

    public virtual QuranCircle Circle { get; set; }

    public virtual RegisterForm Student { get; set; }

    public virtual Teacher Teacher { get; set; }

    public virtual ICollection<TestBody> TestBodies { get; set; } = new List<TestBody>();
}