// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class TestBody
{
    public int Id { get; set; }

    public int TestHeadId { get; set; }

    public string QuestionName { get; set; }

    public int QuestionOrder { get; set; }

    public int TestDegree { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TestHead TestHead { get; set; }
}