// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class WhatsappPreConfiguredMessage
{
    public int Id { get; set; }

    public string WhatsappMessage { get; set; }

    public string Event { get; set; }

    public bool IsEnabled { get; set; }
}