// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class WhatsappTempTable
{
    public string Message { get; set; }

    public string Image { get; set; }

    public string Mobile { get; set; }

    public int Id { get; set; }

    public int? IsGirl { get; set; }
}