// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class WhatsAppSessionId
{
    public int Id { get; set; }

    public int? MasgedSessionId { get; set; }

    public string MasgedApiKey { get; set; }

    public DateTime? UpdatedAt { get; set; }
}