// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MasgedParentMobileAPI.Models;

public partial class WomanActivity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsVisible { get; set; }

    public bool ForGirl { get; set; }

    public virtual ICollection<RegisterForm> RegisterForms { get; set; } = new List<RegisterForm>();
}